name: clang-format-check

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  formatting-check:
    name: Formatting Check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "18"
          check-path: "src"
          fallback-style: "Google"
